[package]
name = "educode-ai"
version = "0.1.0"
description = "EduCode AI Desktop App"
authors = ["EduCode-AI"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
